### ISSUE TITLE
Build camera class

### ISSUE THREAD

**Issue by fwilliams** [fwilliams/mirror-renderer#1]
## TODO:
- [x] Euler angle rotation
- [x] Set lookat vector
- [x] Set position
- [x] Extract camera matrix
- [x] Projection matrix
- [x] Get up/right/lookat vectors
- [x] Move along lookat
- [x] Strafe left/right
- [x] Strafe up/down
